version: "3"
services:
    www:
        build: ./docker/apache
        expose:
            - 80
        ports:
            - "8080:8080"
            - "1337:1337"
        volumes:
            - ./www:/var/www/html/
            - ./apache/php:/var/www/php.d
            - ./apache/:/docker-entrypoint-init.d
        restart: always
        env_file:
            - .env
        links:
            - db
        networks:
            - default
            - reverse-proxy
    db:
        build: ./docker/mysql
        ports:
            - "3308:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - "8889:80"

networks:
    reverse-proxy:
        external:
            name: reverse-proxy
